
baseurl = "https://faculty.iiit.ac.in/~theory/seminar/"
theme = "hugo-tufte"
title = "Theory Seminar"

pygmentsCodeFences = true

[taxonomies]
  category = "categories" 
  group = "groups"
  series = "series"
  tag = "tags"

[params]
  subtitle = "A fortnightly seminar series at IIIT Hyerabad focused on theoretical talks from computer science, communications theory, machine learning and natural sciences."
  copyrightHolder = "IIIT Hyderabad"
  showPoweredBy = true
  instWebsite = "http://iiit.ac.in"

  
# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Upcoming Talks"
  weight = -110 
  identifier = "home"
  url = "/#upcoming"
[[menu.nav]]
  name = "Past Talks"
  weight = -100 
  url = "/#past"
[[menu.nav]]
  name = "Give a Talk"
  weight = -90 
  url = "/#giving-talks"
[[menu.nav]]
  name = "Want to keep notified?"
  weight = -90 
  identifier = "categories"
  url = "/#more-info"




# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------
# [[menu.footer]]
#  name = ""
#  pre = "<i class='fa fa-github fa-2x'></i> "
#  weight = -100 
#  identifier = "github"
#  url = "https://github.com/shawnohare/hugo-tufte"
#[[menu.footer]]
#  name = ""
#  pre = "<i class='fa fa-twitter fa-2x'></i> "
#  weight = -90 
#  identifier = "twitter"
#  url = "https://twitter.com"
